[package]
name = "yahtzee_upper"
version = "0.1.0"
authors = ["peder.august <peder.august@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
